const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let roster={managers:[]},data={team_records:{},updated_at:null},games=[];
const key=(sport,team)=>`${sport}|${team}`;
function pts(p){const r=data.team_records?.[key(p.sport,p.team)]||{wins:0,losses:0,ties:0};return p.side==='Winner'?r.wins:r.losses}
function current(m){return m.picks.reduce((a,p)=>a+pts(p),0)}
function render(){const rows=roster.managers.map(m=>({m,points:current(m)})).sort((a,b)=>b.points-a.points||a.m.manager.localeCompare(b.m.manager));const max=Math.max(1,...rows.map(x=>x.points));
$('#updated').textContent=`Data: ${data.updated_at?new Date(data.updated_at).toLocaleString(): 'local roster / awaiting sync'}`;
$('#hero').innerHTML=rows.slice(0,3).map((x,i)=>`<div class="tile"><div class="muted">${i===0?'LEADER':i===1?'2ND':'3RD'}</div><h2>${esc(x.m.manager)}</h2><div class="metric">${x.points}</div><div class="muted">current points</div><div class="bar"><i style="width:${Math.round(x.points/max*100)}%"></i></div></div>`).join('');
$('#projection').innerHTML='<div class="row head"><span>#</span><span>Manager</span><span>Current</span><span>Expected</span><span>Projected</span></div>'+rows.map((x,i)=>`<div class="row"><span>${i+1}</span><b>${esc(x.m.manager)}</b><span>${x.points}</span><span>—</span><span class="accent">${x.points}</span></div>`).join('');
$('#standings-table').innerHTML='<div class="row head"><span>#</span><span>Manager</span><span>CFB</span><span>NFL</span><span>Total</span></div>'+rows.map((x,i)=>{let c=x.m.picks.filter(p=>p.sport==='CFB').reduce((a,p)=>a+pts(p),0),n=x.points-c;return `<div class="row"><span>${i+1}</span><b>${esc(x.m.manager)}</b><span>${c}</span><span>${n}</span><b>${x.points}</b></div>`}).join('');
$('#manager-list').innerHTML=roster.managers.map(m=>`<div class="card manager"><h3>${esc(m.manager)}</h3><p class="muted">Seed ${m.seed}</p>${m.picks.map(p=>{const r=data.team_records?.[key(p.sport,p.team)]||{wins:0,losses:0,ties:0};return `<div class="pick"><span><span class="tag">${p.sport} ${p.side}</span> ${esc(p.team)}</span><b>${pts(p)}</b></div>`}).join('')}</div>`).join('');
const teams={};roster.managers.forEach(m=>m.picks.forEach(p=>{const k=key(p.sport,p.team);(teams[k]??=[]).push({m:m.manager,side:p.side})}));$('#team-table').innerHTML='<div class="row head"><span>Sport</span><span>Team</span><span>Record</span><span>Managers</span><span>Pts/pick</span></div>'+Object.entries(teams).sort().map(([k,ms])=>{const [sport,team]=k.split('|'),r=data.team_records?.[k]||{wins:0,losses:0,ties:0};return `<div class="row"><span>${sport}</span><b>${esc(team)}</b><span>${r.wins}-${r.losses}-${r.ties||0}</span><span>${ms.map(x=>esc(x.m)).join(', ')}</span><span>${ms.reduce((a,x)=>a+(x.side==='Winner'?r.wins:r.losses),0)/ms.length}</span></div>`}).join('');
$('#games-list').innerHTML=games.length?games.map(g=>`<div class="card ${g.status==='in'?'live':''}"><b>${esc(g.sport)} • ${esc(g.statusText||'Scheduled')}</b><h3>${esc(g.away)} ${g.awayScore??''} — ${g.homeScore??''} ${esc(g.home)}</h3><p class="muted">${g.probability!=null?`Win probability: ${Math.round(g.probability*100)}%`:''}</p></div>`).join(''):'<div class="card"><b>No live game feed yet.</b><p class="muted">Automatic synchronization will populate this panel.</p></div>';
$('#impact').innerHTML=roster.managers.map(m=>{let v=0; m.picks.forEach(p=>{const g=games.find(x=>x.away===p.team||x.home===p.team);if(g?.probability!=null)v+=p.side==='Winner'?g.probability:1-g.probability});return `<div class="card"><b>${esc(m.manager)}</b><div class="metric">${v?v.toFixed(1):'—'}</div><span class="muted">live expected points</span></div>`}).join('')}
async function load(){try{roster=await fetch('data/rosters.json').then(r=>r.json());data=await fetch('data/standings.json').then(r=>r.json())}catch(e){console.error(e);return}render()}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});load();setInterval(load,300000);